Drink.create!(:name => "Red Wine", :desc => "Made from red grapes")
Drink.create!(:name => "White Wine", :desc => "Sprite in disguise")
Drink.create!(:name => "Beer", :desc => "Oktoberfest")
Drink.create!(:name => "Vodka", :desc => "Da!")
Drink.create!(:name => "Gin", :desc => "Rhymes with chin")
Drink.create!(:name => "Rum", :desc => "Yar har me matey!")
Drink.create!(:name => "Fireball", :desc => "Who thought this was a good idea?")
Drink.create!(:name => "Whiskey", :desc => "It'll put hair on your chest")
Drink.create!(:name => "Amaretto", :desc => "Tastes like jolly ranchers")
Drink.create!(:name => "Moonshine", :desc => "Made from corn")
Drink.create!(:name => "Screwdriver", :desc => "Vodka and orange juice")
Drink.create!(:name => "White Russian", :desc => "An unlikely combination")
Drink.create!(:name => "Tequila", :desc => "With or without worm")
Drink.create!(:name => "Bailey's", :desc => "Pure bliss")
Drink.create!(:name => "Water", :desc => "The original drink")




Bread.create!(:name => "Rye", :desc => "Great for reubens")
Bread.create!(:name => "French", :desc => "Crunchy")
Bread.create!(:name => "White", :desc => "The standard")
Bread.create!(:name => "Wheat", :desc => "The healthy")
Bread.create!(:name => "Sourdough", :desc => "You'll never know when it's gone bad")
Bread.create!(:name => "Oat Filled", :desc => "Even Healthier")
Bread.create!(:name => "Avocado", :desc => "Bread of the millennial")
Bread.create!(:name => "Pita", :desc => "Pretentious")
Bread.create!(:name => "Naan", :desc => "Amazing")
Bread.create!(:name => "Baguette", :desc => "Frencher than French")
Bread.create!(:name => "Brioche", :desc => "Sounds fancy")
Bread.create!(:name => "Crouton", :desc => "Good in soup")
Bread.create!(:name => "Pretzel", :desc => "Is this even bread?")
Bread.create!(:name => "Pumpernickel", :desc => "Fun to say")
Bread.create!(:name => "Teacake", :desc => "English bread")
Bread.create!(:name => "Toast", :desc => "Birthed from a toaster")

Pair.create!(:drink => "Red Wine", :bread => "French", :desc => "Catholics Delight")
